### ISSUE TITLE
Trim description

### ISSUE THREAD

**Issue by pauldijou** [PolymerElements/iron-elements#10]
The current version of Bower invalid any package with a [description longer than 140 characters](https://github.com/bower/json/blob/cbadab875639e7c65f8c51b34311bcae142a8066/lib/json.js#L107-L109). Any chance to trim the description of this package to make it a valid Bower JSON?

Thanks!

**Comment by arthurvr** [comment]
https://github.com/PolymerElements/iron-elements/pull/11

**Comment by pauldijou** [comment]
My bad, missed that PR. Thanks for pointing it @arthurvr
