### ISSUE TITLE
About iron-list

### ISSUE THREAD

**Issue by MartinMoizard** [PolymerElements/iron-elements#12]
Hello,

Is there a release date planned for the iron-list? I need to build an element that would really benefit from this component. 

Also, if the release date is not in the near future, would it be possible for you to provide an alpha version?

Thanks a lot,
Martin

**Comment by brianzable** [comment]
Also curious about the ETA on iron-list. I spiked out an app that was heavily dependent on core-list using Polymer 0.5 and went on to build the production version using 1.0 under the assumption that iron-list would be there.

**Comment by rmayhue** [comment]
Same here.  The ETA on the README has been "Couple weeks" for quite a while now.  Can someone on the Polymer team please provide an update as to the status? Thanks!

**Comment by chillitom** [comment]
:+1:

**Comment by christoth** [comment]
+1

**Comment by notthetup** [comment]
:+1:

**Comment by EduardoNavarro** [comment]
Same here! Can we do something to help or speed up the process of porting core to iron list?

**Comment by tzolov** [comment]
+1 
indeed is there something we can help to speed up the process?

**Comment by Wurper** [comment]
+1
:crystal_ball: what will the future hold for the iron list?

**Comment by jshcrowthe** [comment]
+1

**Comment by blasten** [comment]
iron-list is almost there :) I'm fixing some issues in mobile Safari & Chrome.

**Comment by EduardoNavarro** [comment]
Hi Blasten,  is there something i can do for help?
Amost there sounds great!

**Comment by robfrawley** [comment]
@blasten Can you, at the very least, update the readme to provide an actual timeframe? According to Google "couple" is defined as two, not four moving toward 5: https://www.google.com/search?q=couple+definition.

**Comment by binoculars** [comment]
👍

**Comment by social4hyq** [comment]
+1

**Comment by pdf** [comment]
Initial release of iron-list is available: https://github.com/PolymerElements/iron-list

This issue should be closed.
