### ISSUE TITLE
land iron-list

### ISSUE THREAD

**Issue by tjsavage** [PolymerElements/iron-elements#13]
Tracking issue for `iron-list`

@kevinpschaaf & @blasten

**Comment by tzolov** [comment]
+1

**Comment by blasten** [comment]
It's on its way. :)

**Comment by EduardoNavarro** [comment]
Tell us if we can do something to help with iron-list testing or bug fixing

**Comment by gertcuykens** [comment]
Last time I wanted something this bad was when half life 2 came out, just saying :)

**Comment by blasten** [comment]
sure!

**Comment by SignpostMarv** [comment]
how's the grid-based layout looking for iron-list?

**Comment by binoculars** [comment]
:+1: for this and :+1: for grid layout

**Comment by blasten** [comment]
**iron-list** is now available https://github.com/PolymerElements/iron-list !
Demo: http://blasten.github.io/elements/iron-list/demo/index.html?code=1
- `v1` includes vertical scrolling variable height list, and we have published a roadmap for future features on https://github.com/PolymerElements/iron-list/issues/10.  Feel free to comment any the features and/or send PRs!

**Comment by Sinjins** [comment]
+1
