### ISSUE TITLE
Install via bower shows EINVALID

### ISSUE THREAD

**Issue by fooloomanzoo** [PolymerElements/iron-elements#16]
The bower output shows the message "The description is too long"
![image](https://cloud.githubusercontent.com/assets/9318952/8499973/4e4b0796-2198-11e5-9c0d-15b67cf5c01d.png)

**Comment by JonathanMartel** [comment]
Have the same issue right now.

**Comment by fooloomanzoo** [comment]
In my case, I reinstalled node, npm and bower to the newist version and then it worked
