### ISSUE TITLE
Element request: iron-datetime

### ISSUE THREAD

**Issue by abdonrd** [PolymerElements/iron-elements#33]
Are there any plans to create an element to manage dates and time?

Something like this?

``` html
<iron-datetime></iron-datetime>
// Sun Jan 10 2016 19:02:04 GMT+0100 (CET)

<iron-datetime datetime="2016-01-01T10:00:00.182Z"></iron-datetime>
// Sun Jan 1 2016 10:00:00 GMT+0100 (CET)

<iron-datetime datetime="2016-01-01T10:00:00.182Z" format="YYYY-MM-DD"></iron-datetime>
// 2016-01-01
```

**Comment by cdata** [comment]
We are planning to build a datepicker eventually. The element you are proposing doesn't seem like it will be a datepicker, though. Can you go into more detail about the usecases for an `iron-datetime` element as you imagine it?

**Comment by abdonrd** [comment]
@cdata a very good example is the all the times in GitHub:

<img width="298" alt="screen shot 2016-02-04 at 21 30 46" src="https://cloud.githubusercontent.com/assets/1007051/12828720/b275f0e4-cb86-11e5-9e2b-01d340d0b33c.png">

<img width="492" alt="screen shot 2016-02-04 at 21 30 58" src="https://cloud.githubusercontent.com/assets/1007051/12828725/b69bc7ac-cb86-11e5-9ac4-d5ee1035761d.png">

<img width="297" alt="screen shot 2016-02-04 at 21 31 30" src="https://cloud.githubusercontent.com/assets/1007051/12828729/ba229f86-cb86-11e5-9ef0-7f8eb9e8c783.png">

**Comment by abdonrd** [comment]
Closing very old issue...
