### ISSUE TITLE
bower install also installs several paper elements plus neon-animation

### ISSUE THREAD

**Issue by miztroh-zz** [PolymerElements/iron-elements#34]
Running the following command produces the output shown below.  Seems odd that installing iron-elements should also install some paper-elements and neon-animation.

`bower install --save PolymerElements/iron-elements`

iron-elements#1.0.7 bower_components\iron-elements
├── iron-a11y-announcer#1.0.4
├── iron-a11y-keys#1.0.4
├── iron-a11y-keys-behavior#1.1.0
├── iron-ajax#1.1.1
├── iron-autogrow-textarea#1.0.10
├── iron-behaviors#1.0.12
├── iron-checked-element-behavior#1.0.4
├── iron-collapse#1.0.5
├── iron-component-page#1.1.3
├── iron-demo-helpers#1.0.3
├── iron-doc-viewer#1.0.12
├── iron-dropdown#1.1.0
├── iron-fit-behavior#1.0.5
├── iron-flex-layout#1.2.2
├── iron-form#1.0.13
├── iron-form-element-behavior#1.0.6
├── iron-icon#1.0.7
├── iron-icons#1.1.1
├── iron-iconset#1.0.4
├── iron-iconset-svg#1.0.9
├── iron-image#1.0.4
├── iron-input#1.0.8
├── iron-jsonp-library#1.0.4
├── iron-label#1.0.1
├── iron-list#1.1.7
├── iron-localstorage#1.0.5
├── iron-media-query#1.0.8
├── iron-menu-behavior#1.0.7
├── iron-meta#1.1.1
├── iron-overlay-behavior#1.1.2
├── iron-page-url#0.7.0
├── iron-pages#1.0.5
├── iron-range-behavior#1.0.4
├── iron-resizable-behavior#1.0.2
├── iron-selector#1.0.8
├── iron-signals#1.0.3
├── iron-swipeable-container#1.0.2
├── iron-test-helpers#1.1.3
├── iron-validatable-behavior#1.0.5
└── iron-validator-behavior#1.0.1

iron-a11y-announcer#1.0.4 bower_components\iron-a11y-announcer
└── polymer#1.2.3

iron-ajax#1.1.1 bower_components\iron-ajax
├── polymer#1.2.3
└── promise-polyfill#1.0.0

iron-a11y-keys-behavior#1.1.0 bower_components\iron-a11y-keys-behavior
└── polymer#1.2.3

iron-a11y-keys#1.0.4 bower_components\iron-a11y-keys
├── iron-a11y-keys-behavior#1.1.0
└── polymer#1.2.3

iron-autogrow-textarea#1.0.10 bower_components\iron-autogrow-textarea
├── iron-behaviors#1.0.12
├── iron-flex-layout#1.2.2
├── iron-form-element-behavior#1.0.6
├── iron-validatable-behavior#1.0.5
└── polymer#1.2.3

iron-fit-behavior#1.0.5 bower_components\iron-fit-behavior
└── polymer#1.2.3

iron-form#1.0.13 bower_components\iron-form
├── iron-ajax#1.1.1
└── polymer#1.2.3

iron-icon#1.0.7 bower_components\iron-icon
├── iron-flex-layout#1.2.2
├── iron-meta#1.1.1
└── polymer#1.2.3

iron-swipeable-container#1.0.2 bower_components\iron-swipeable-container
└── polymer#1.2.3

iron-jsonp-library#1.0.4 bower_components\iron-jsonp-library
└── polymer#1.2.3

iron-iconset#1.0.4 bower_components\iron-iconset
├── iron-meta#1.1.1
└── polymer#1.2.3

iron-image#1.0.4 bower_components\iron-image
├── iron-flex-layout#1.2.2
└── polymer#1.2.3

iron-localstorage#1.0.5 bower_components\iron-localstorage
└── polymer#1.2.3

iron-iconset-svg#1.0.9 bower_components\iron-iconset-svg
├── iron-meta#1.1.1
└── polymer#1.2.3

iron-meta#1.1.1 bower_components\iron-meta
└── polymer#1.2.3

iron-range-behavior#1.0.4 bower_components\iron-range-behavior
└── polymer#1.2.3

iron-selector#1.0.8 bower_components\iron-selector
└── polymer#1.2.3

iron-checked-element-behavior#1.0.4 bower_components\iron-checked-element-behavior
├── iron-form-element-behavior#1.0.6
├── iron-validatable-behavior#1.0.5
└── polymer#1.2.3

iron-demo-helpers#1.0.3 bower_components\iron-demo-helpers
├── marked-element#1.1.1
├── paper-styles#1.1.2
├── polymer#1.2.3
└── prism-element#1.0.3

iron-resizable-behavior#1.0.2 bower_components\iron-resizable-behavior
└── polymer#1.2.3

iron-signals#1.0.3 bower_components\iron-signals
└── polymer#1.2.3

iron-validator-behavior#1.0.1 bower_components\iron-validator-behavior
├── iron-meta#1.1.1
└── polymer#1.2.3

iron-dropdown#1.1.0 bower_components\iron-dropdown
├── iron-a11y-keys-behavior#1.1.0
├── iron-behaviors#1.0.12
├── iron-overlay-behavior#1.1.2
├── iron-resizable-behavior#1.0.2
├── neon-animation#1.0.9
└── polymer#1.2.3

prism-element#1.0.3 bower_components\prism-element
├── polymer#1.2.3
└── prism#1.3.0

iron-validatable-behavior#1.0.5 bower_components\iron-validatable-behavior
├── iron-meta#1.1.1
└── polymer#1.2.3

iron-label#1.0.1 bower_components\iron-label
└── polymer#1.2.3

promise-polyfill#1.0.0 bower_components\promise-polyfill
└── polymer#1.2.3

iron-flex-layout#1.2.2 bower_components\iron-flex-layout
└── polymer#1.2.3

iron-page-url#0.7.0 bower_components\iron-page-url
└── polymer#1.2.3

prism#1.3.0 bower_components\prism

iron-collapse#1.0.5 bower_components\iron-collapse
└── polymer#1.2.3

iron-behaviors#1.0.12 bower_components\iron-behaviors
├── iron-a11y-keys-behavior#1.1.0
└── polymer#1.2.3

iron-component-page#1.1.3 bower_components\iron-component-page
├── hydrolysis#1.21.4
├── iron-ajax#1.1.1
├── iron-doc-viewer#1.0.12
├── iron-flex-layout#1.2.2
├── iron-icons#1.1.1
├── iron-selector#1.0.8
├── paper-header-panel#1.1.2
├── paper-styles#1.1.2
├── paper-toolbar#1.1.2
└── polymer#1.2.3

iron-form-element-behavior#1.0.6 bower_components\iron-form-element-behavior
└── polymer#1.2.3

hydrolysis#1.21.4 bower_components\hydrolysis

iron-input#1.0.8 bower_components\iron-input
├── iron-validatable-behavior#1.0.5
└── polymer#1.2.3

iron-pages#1.0.5 bower_components\iron-pages
├── iron-resizable-behavior#1.0.2
├── iron-selector#1.0.8
└── polymer#1.2.3

marked-element#1.1.1 bower_components\marked-element
├── marked#0.3.5
└── polymer#1.2.3

iron-media-query#1.0.8 bower_components\iron-media-query
└── polymer#1.2.3

iron-menu-behavior#1.0.7 bower_components\iron-menu-behavior
├── iron-a11y-keys-behavior#1.1.0
├── iron-selector#1.0.8
└── polymer#1.2.3

iron-test-helpers#1.1.3 bower_components\iron-test-helpers
└── polymer#1.2.3

iron-overlay-behavior#1.1.2 bower_components\iron-overlay-behavior
├── iron-fit-behavior#1.0.5
├── iron-resizable-behavior#1.0.2
└── polymer#1.2.3

iron-doc-viewer#1.0.12 bower_components\iron-doc-viewer
├── marked-element#1.1.1
├── paper-button#1.0.11
├── paper-styles#1.1.2
├── polymer#1.2.3
└── prism-element#1.0.3

iron-icons#1.1.1 bower_components\iron-icons
├── iron-icon#1.0.7
├── iron-iconset-svg#1.0.9
└── polymer#1.2.3

paper-styles#1.1.2 bower_components\paper-styles
├── font-roboto#1.0.1
├── iron-flex-layout#1.2.2
└── polymer#1.2.3

marked#0.3.5 bower_components\marked

paper-header-panel#1.1.2 bower_components\paper-header-panel
├── iron-flex-layout#1.2.2
└── polymer#1.2.3

paper-toolbar#1.1.2 bower_components\paper-toolbar
├── iron-flex-layout#1.2.2
├── paper-styles#1.1.2
└── polymer#1.2.3

font-roboto#1.0.1 bower_components\font-roboto

iron-list#1.1.7 bower_components\iron-list
├── iron-resizable-behavior#1.0.2
└── polymer#1.2.3

neon-animation#1.0.9 bower_components\neon-animation
├── iron-meta#1.1.1
├── iron-resizable-behavior#1.0.2
├── iron-selector#1.0.8
├── paper-styles#1.1.2
├── polymer#1.2.3
└── web-animations-js#2.1.3

paper-button#1.0.11 bower_components\paper-button
├── iron-flex-layout#1.2.2
├── paper-behaviors#1.0.10
├── paper-material#1.0.5
├── paper-ripple#1.0.5
└── polymer#1.2.3

paper-behaviors#1.0.10 bower_components\paper-behaviors
├── iron-behaviors#1.0.12
├── iron-checked-element-behavior#1.0.4
└── polymer#1.2.3

paper-ripple#1.0.5 bower_components\paper-ripple
├── iron-a11y-keys-behavior#1.1.0
└── polymer#1.2.3

paper-material#1.0.5 bower_components\paper-material
├── paper-styles#1.1.2
└── polymer#1.2.3

web-animations-js#2.1.3 bower_components\web-animations-js

**Comment by ebidel** [comment]
Why is that weird? The animations provided by https://github.com/PolymerElements/neon-animation/tree/master/animations is a dependency to iron-dropdown like any other dependency.

**Comment by miztroh-zz** [comment]
OK, neon-animation is more understandable.  But, what about the paper elements?

**Comment by notwaldorf** [comment]
They are dev dependencies, used in some of the demos.
