### ISSUE TITLE
New element: iron-lazy-pages

### ISSUE THREAD

**Issue by TimvdLippe** [PolymerElements/iron-elements#43]
Last week I created [`iron-lazy-pages`](https://github.com/TimvdLippe/iron-lazy-pages) and by popular demand I want to propose this element as a new iron-element.

The README shows the features of the element as well as some basic documentation of how it supposed to work (includes timing and API). I have not yet documented the actual element, but I have tested it in a [sample application](https://github.com/TimvdLippe/polymer-lazy-application) (example usage [here](https://github.com/TimvdLippe/polymer-lazy-application/blob/master/app/index.html#L16-L36)). Actual unit tests have yet to be written. Please let me know what you think!

**Comment by tjsavage** [comment]
Hey @TimvdLippe wanted to quickly follow-up - we're currently broadly looking at what the best way down the line to load components might be: whether it will be lazily in bundles, or granularly via HTTP2. We're in the process of running some experiments here, and based on the findings will be able to take a closer look at `iron-lazy-pages` and see if it's something that could be "official."

In the meantime, we're also looking for better ways to enable sharing of elements and making elements more discoverable, and decreasing the need for things to be "official." This is totally a useful component regardless, and it's a bummer that needing to be in PolymerElements/ is seen as a prerequisite. Don't want to derail the thread here, but would love thoughts on how to make components more shareable.

**Comment by TimvdLippe** [comment]
@tjsavage Thanks for replying, somehow this issue slipped through my inbox.

The major reason I wanted to propose this element to be made official is because the PSK v2 could use the element, however the PSK only uses official elements. So in that sense it was seen as a prerequisite by me.

That said, I will close this issue for now and might reopen after the resolution of https://github.com/Polymer/project/issues/21. Thank you for your consideration!
