### ISSUE TITLE
Make it easier for users to run element demos

### ISSUE THREAD

**Issue by sorvell** [PolymerElements/iron-elements#7]
Because the demos often contain devDependencies, running them currently requires either using `polyserve` or moving elements manually.

Can this be made easier?

**Comment by morethanreal** [comment]
Hmm... I consider `bower install` and `polyserve` pretty easy. What is easier?

**Comment by mbleigh** [comment]
You can also view the demos by visiting the element page on the catalog and clicking the demo on the side (there will be direct deep links but there's a bug for direct demo links atm)

**Comment by cdata** [comment]
I agree with @sorvell : Bower sucks. Let's build something better than Bower.

**Comment by fearphage** [comment]
We already have something better than bower. It's called npm.

**Comment by mbleigh** [comment]
Very difficult to come up with a better solution than Bower until there's better de-duplication support in HTML Imports or a lower-level module loader spec.

**Comment by notwaldorf** [comment]
Assigning it to AJ to see if the `wcw` tool can address this

**Comment by garlicnation** [comment]
`wcw install -r PolymerElements/iron-elements && http-server`

**Comment by garlicnation** [comment]
At least if https://github.com/PolymerLabs/web-component-workspace/pull/1 is merged.

**Comment by notwaldorf** [comment]
`polygit`and `polyserve` both do this, I think we can close this thread :)

**Comment by fearphage** [comment]
@notwaldorf @garlicnation FYI PolymerLabs/web-component-workspace is still a private repo.
