### ISSUE TITLE
core-scroll-threshold

### ISSUE THREAD

**Issue by emmanuelbuah** [PolymerElements/iron-elements#9]
Is there any chance to migration core-scroll-threshold?

**Comment by eximius313** [comment]
+1

**Comment by notwaldorf** [comment]
Assigning to @tjsavage for triage

**Comment by grokys** [comment]
+1

**Comment by eximius313** [comment]
any update on this one?

**Comment by notwaldorf** [comment]
Yup! This has been ported to https://github.com/PolymerElements/iron-scroll-threshold
